"""One-time font asset maintenance, not required by the website build.

After building the site, run with Python + fonttools[woff] installed:
  python3 scripts/subset-font.py /path/to/SourceHanSansTW-VF.ttf.woff2
The upstream font and license are pinned in docs/FONTS.md.
"""
from html.parser import HTMLParser
from pathlib import Path
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path(sys.argv[1])
DEST = ROOT / 'src/assets/fonts'


class VisibleText(HTMLParser):
    def __init__(self):
        super().__init__()
        self.text = []
        self.hidden = 0

    def handle_starttag(self, tag, attrs):
        self.hidden += tag in ('script', 'style')
        for key, value in attrs:
            if key in ('placeholder', 'aria-label', 'title', 'alt') and value:
                self.text.append(value)

    def handle_endtag(self, tag):
        self.hidden -= tag in ('script', 'style')

    def handle_data(self, text):
        if not self.hidden:
            self.text.append(text)


def characters(path):
    parser = VisibleText()
    parser.feed(path.read_text())
    return set(map(ord, ''.join(parser.text)))


def unicode_ranges(points):
    runs = []
    for point in sorted(points):
        if runs and point == runs[-1][1] + 1:
            runs[-1][1] = point
        else:
            runs.append([point, point])
    return ','.join(f'U+{a:X}' if a == b else f'U+{a:X}-{b:X}' for a, b in runs)


cmap = set(TTFont(SOURCE).getBestCmap())
latin = {c for c in cmap if c < 0x300 or 0x2000 <= c <= 0x206F}
home = characters(ROOT / 'dist/index.html') & cmap - latin
content = set().union(*(characters(p) for p in (ROOT / 'dist').rglob('*.html')))
content = content & cmap - latin - home
groups = {'latin': latin, 'home': home, 'content': content,
          'extended': cmap - latin - home - content}
DEST.mkdir(parents=True, exist_ok=True)
css = ['/* Generated by scripts/subset-font.py; see docs/FONTS.md. */']
for label, points in groups.items():
    font = TTFont(SOURCE)
    options = subset.Options()
    options.name_IDs = ['*']
    options.name_languages = ['*']
    options.name_legacy = True
    # OFL reserves "Source": derived subsets use a distinct family name.
    for record in font['name'].names:
        if record.nameID in (1, 3, 4, 6, 16, 25):
            value = 'SAT Han Sans TC' if record.nameID in (1, 4, 16) else 'SATHanSansTC'
            record.string = value.encode(record.getEncoding())
    worker = subset.Subsetter(options=options)
    worker.populate(unicodes=points)
    worker.subset(font)
    output = DEST / f'sat-han-sans-tc-{label}.woff2'
    font.flavor = 'woff2'
    font.save(output)
    css.append('@font-face {\n  font-family: "SAT Han Sans TC";\n'
               f'  src: url("../assets/fonts/{output.name}") format("woff2");\n'
               '  font-style: normal;\n  font-weight: 250 900;\n'
               '  font-display: swap;\n'
               f'  unicode-range: {unicode_ranges(points)};\n}}')
    print(label, len(points), 'characters,', output.stat().st_size, 'bytes')
(ROOT / 'src/styles/fonts.css').write_text('\n\n'.join(css) + '\n')
